server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/dev/msa_all/native-file-repo
        git:
#          uri: file:///Users/jeongseung-gu/dev/msa_all/git-local-repo
          uri: https://github.com/jsggo2001/spring-cloud-config.git
          username: {username}
          password: {password}
#          username과 password는 public repo에서는 필요없지만 만약 privete repo라면 설정 해 주어야 된다

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
